---

- include: "repo-{{ ansible_os_family }}.yml"
  when: grafana_install_repo != ""

- include: install.yml
- include: configure.yml
- include: provisioning.yml

- name: Start and enable the Grafana service
  service:
    name: grafana-server
    state: started
    enabled: true
